<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>formulaire de Connexion</title>
</head>
<body>
    <form method="post" action="../Managers/CheckRegister.php">
            <fieldset>
                <label for="first_name">
                    Prenom
                </label>
                <input type="text" name="firstname" id="firstname" />
            </fieldset>
            <fieldset>
                <label for="last_name">
                    Nom
                </label>
                <input type="text" name="lastname" id="lastname" />
            </fieldset>
            <fieldset>
                <label for="last_name">
                    Nom d'utilisateur
                </label>
                <input type="text" name="username" id="username" />
            </fieldset>
            <fieldset>
                <label for="email">
                    E-mail
                </label>
                <input type="email" name="email" id="email" />
            </fieldset>
            <fieldset>
                <label for="password">
                    Password
                </label>
                <input type="password" name="password" id="password" />
            </fieldset>
            <fieldset>
                <button type="submit">Envoyer</button>
            </fieldset>
        </form>
    
</body>
</html>