<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>formulaire de Connexion</title>
</head>
<body>
    <form method="post" action="index.php?route=check-connexion">
            
            <fieldset>
                <label for="last_name">
                    Nom d'utilisateur
                </label>
                <input type="text" name="username" id="username" />
            </fieldset>
            <fieldset>
                <label for="password">
                    Password
                </label>
                <input type="password" name="password" id="password" />
            </fieldset>
            <fieldset>
                <button type="submit">Envoyer</button>
            </fieldset>
        </form>
</body>
</html>