<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Auth MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						
					</li>
					<li>
						
					</li>
					
				</ul>
			</nav>
			<fieldset>
                <button type="submit">
                	<a href="index.php?route=inscription">S'inscrire</a>
                </button>
            </fieldset>
            <fieldset>
                <button type="submit">
                	<a href="index.php?route=connexion">se connecter</a>
                </button>
            </fieldset>
		</header>
		<?php
		require "templates/$template.phtml";
		?>
	</body>
</html>