<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf8" />
        <title> Exercice Authentification MVC</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="index.php?route=login">Login</a>
                    </li>
                    <li>
                        <a href="index.php?route=register">Register</a>
                    </li>
                    <li>
                        <a href="index.php?route=profile">Profile</a>
                    </li>
                    <li>
                        <a href="index.php?route=logout">Logout</a>
                    </li>
                </ul>
            </nav>
        </header>
        <?php
            require "templates/$template.phtml";
        ?>
    </body>
</html>