<main>
    <h1>
        Login
    </h1>
    <form action="index.php?route=check-login" method="POST">
        <fieldset>
            <label for="email">
                Email
            </label>
            <input type="email" id="email" name="email" />
        </fieldset>
        <fieldset>
            <label for="password">
                Password
            </label>
            <input type="password" id="password" name="password" />
        </fieldset>
        <button type="submit">Login</button>
    </form>
</main>