<main>
    <h1>
        Register
    </h1>
    <form action="index.php?route=check-register" method="POST">
        <fieldset>
            <label for="username">
                Username
            </label>
            <input type="text" id="username" name="username" />
        </fieldset>
        <fieldset>
            <label for="email">
                Email
            </label>
            <input type="email" id="email" name="email" />
        </fieldset>
        <fieldset>
            <label for="password">
                Password
            </label>
            <input type="password" id="password" name="password" />
        </fieldset>
        <button type="submit">Register</button>
    </form>
</main>